### PR TITLE
Create icarAnimalEventCoreResource

### LINKED ISSUE #290: Create icarAnimalEventCoreResource
In order to implement the discussion on #273 we decided to:
* Remove the `animal` property from icarEventCoreResource.json
* Create a new icarAnimalEventCoreResource.json which references icarEventCoreResource.json with allof and adds the `animal` property.
* Change all the existing individual animal events to reference icarAnimalEventCoreResource.json instead.

The net result to implementers is no change (nothing broken), but we will then be able to add group events based on icarEventCoreResource.json as well.

### PR DESCRIPTION
**Pull request by cookeac**
This PR resolves #290
* Removes `animal` property from icarEventCoreResource
* Creates icarAnimalEventCoreResource which incorporates icarEventCoreResource and adds `animal` property
* Changes all event instances to incorporate icarAnimalEventCoreResource instead.

### CODE REVIEW

**Comment by erwinspeybroeck** [comment]
I agree with this pull request. No remarks.

**Review by erwinspeybroeck — APPROVED** [review]
Agreed - no remarks

**Comment by AndreasSchultzGEA** [comment]
Why do we need this additional new 'AnimalEventCoreResource' as at the moment, no other file seems to inherit from 'IcarEventCoreResource'.
All other resources seem to be prefixed with 'Icar'. Except for an exception-resource. This new one not.

**Review by AndreasSchultzGEA — APPROVED** [review]
no more comments

**Pull request merged**
