### PR TITLE
Changes for parturition event with new progeny details

### PR DESCRIPTION
**Pull request by ahokkonen**
Resolves adewg/ICAR#191

Added new types for progeny details and enumeration parameters for progeny birth statuses.
**Note**! _This is a draft PR - work is still in progress and will be progressed after first reviews/comments._

### CODE REVIEW

**Review by erwinspeybroeck — APPROVED** [review]
Looks good to me. I wonder if it would not be better to leave out the progeny array at all - but probably needed for backwards compatibility I guess - for version 2.0 ....

**Comment by ahokkonen** [comment]
@erwinspeybroeck as far as I remember we agreed on leaving the original array, but marking it as 'deprecated'. And we can then remove it completely in 2.x

**Comment by dirbSEGES** [comment]
Hi, what about the birthWeigtScore?

**Comment by cookeac** [comment]
This is in progress. We discussed at the last meeting how these "scores" could be handled as enumerations, but I also remind you that you can always extend the schema for days that only your country or application uses.


________________________________

**Comment by ahokkonen** [comment]
@erwinspeybroeck @dirbSEGES

New field is added for "birthSize" using enumeration for common codes.

@cookeac I'm still a bit unsure we we want to use Resource based type for icarParturitionProgenyDetailsType, any reason for having it like that?

**Comment by ahokkonen** [comment]
One thing in addition - should also sire information be added for the progeny details or for the parturition event?

**Comment by erwinspeybroeck** [comment]
looking from our perspective I would say no sire information to be added there. We always derive the sire based on reproduction events

**Comment by dirbSEGES** [comment]
The same from our perspective

**Comment by ahokkonen** [comment]
Added a few changes - I guess having "DiedBeforeTaggingDate" instead of a "DiedBeforeOfficialRegistrationDate" is a more correct term. What you think @erwinspeybroeck @dirbSEGES @cookeac

**Comment by dirbSEGES** [comment]
Ok, from our side.

**Comment by erwinspeybroeck** [comment]
As long as the definition of what is meant is right - in fact it means the time the farmer has to officially tag the animals, I guess

**Comment by ahokkonen** [comment]
PR opened for the official review
@cookeac @erwinspeybroeck @alamers

**Review by cookeac — APPROVED** [review]

**Pull request merged**
